version: '2'
services:
    backend:
        build: ./back-end/Eshop
        ports:
            - "5000:80"
        depends_on:
          - db
    frontend:
        build: ./front-end
        ports:
         - "3000:8000"
        links:
         - "backend:rest-api"
        stdin_open: true
        tty: true
        depends_on:
          - backend
        environment:
         - NODE_ENV=development
    db:
        image: "microsoft/mssql-server-linux:latest"
        environment:
            SA_PASSWORD: "MyPass@word"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"